name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

jobs:
  check-diff:
    runs-on: ubuntu-latest
    outputs:
      run-tests: ${{ steps.filter.outputs.code }}
    steps:
      - uses: actions/checkout@v6

      - name: Check for changes
        uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            code:
              - 'src/**'
              - 'tests/**'
              - 'uv.lock'

  lint:
    needs: check-diff
    if: needs.check-diff.outputs.run-tests == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: |
          uv venv
          uv sync --dev

      - name: Ruff lint
        run: uv run ruff check src tests

      - name: Ruff format check
        run: uv run ruff format --check src tests

      - name: Pyright
        run: uv run pyright

  test:
    needs: [ check-diff, lint ]
    if: needs.check-diff.outputs.run-tests == 'true'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.14'

      - name: Install uv
        uses: astral-sh/setup-uv@v7

      - name: Install dependencies
        run: |
          uv venv
          uv sync --dev

      - name: Run tests with coverage
        run: |
          uv run pytest --cov=src/rebelist/hack --no-cov-on-fail --cov-report xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          report_type: coverage
          token: ${{ secrets.CODECOV_TOKEN }}
          slug: rebelist/hack